name: Build Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: debug
      run: export
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag http-pong:$(git rev-list HEAD | head -n 1)
