name: Build Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: debug
      env:
        SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      run: export
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "http-pong:$GITHUB_SHA"
